[project]
name = "fastapi-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.115.13",
    "isort>=6.0.1",
    "pydantic>=2.11.7",
    "uvicorn>=0.34.3",
]
