version: 2

models:
  - name: dim_listings_cleansed
    description: cleansed table view for Airbnb listings
    columns:
      - name: listing_id
        description: primary key for listings dimension view
        tests:
          - unique
          - not_null

      - name: host_id
        description: Host ID, referenced to host_id in dim_hosts_cleansed
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: type of room
        tests:
          - accepted_values:
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]

      - name: minimum_nights
        description: "{{ doc('dim_listings_cleansed_minimum_nights') }}"
        tests:
          - positive_value
